name: rewind-ui build

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd rewind-ui && yarn install

      - name: Run build command
        run: cd rewind-ui && yarn build
